version: "3.9"

services:
  db: 
    image: postgres:latest
    ports:
      - "5432:5432"
    command: postgres
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123

