version: "3.9"


services:
  db: 
    image: postgres:latest
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "250MB"

  api01: 
    image: rinha-api-1
    ports:
      - "9999:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: rinha-net
