version: "3.9"

x-common-variables: &common-variables
  DB_HOST: db
  POOL_MAX_CONNECTIONS: 10 

services:
  db: 
    image: postgres:latest
    ports:
      - "5432:5432"
    command: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "460MB"

  api01: 
    image: rinha-api-1
    depends_on:
      - db
    environment:
      <<: *common-variables
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  api02: 
    image: rinha-api-1
    depends_on:
      - db
    environment:
      <<: *common-variables
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

networks:
  default:
    driver: bridge
    name: rinha-net
